CREATE DATABASE IF NOT EXISTS ta_db;
USE ta_db;

CREATE TABLE IF NOT EXISTS menfess (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  nim VARCHAR(30) NOT NULL,
  prodi VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
